export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';
export const CREATE_EVENT_COMPLETE = 'CREATE_EVENT_COMPLETE';

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';
export const UPDATE_EVENT_COMPLETE = 'UPDATE_EVENT_COMPLETE';


export const EVENT_DETAIL_REQUEST = "EVENT_DETAIL_REQUEST";
export const EVENT_DETAIL_SUCCESS = "EVENT_DETAIL_SUCCESS";
export const EVENT_DETAIL_FAIL = "EVENT_DETAIL_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST"; 
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS"; 
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";
export const UPLOAD_IMAGE_COMPLETE = "UPLOAD_IMAGE_COMPLETE";


export const STORE_EVENT_ID = "STORE_EVENT_ID"

export const CLEAR_EVENT_DATA = "CLEAR_EVENT_DATA"

export const PUBLISH_EVENT_REQUEST = "PUBLISH_EVENT_REQUEST"; 
export const PUBLISH_EVENT_SUCCESS = "PUBLISH_EVENT_SUCCESS"; 
export const PUBLISH_EVENT_FAIL = "PUBLISH_EVENT_FAIL"; 
export const PUBLISH_EVENT_COMPLETE = "PUBLISH_EVENT_COMPLETE"; 


export const PUBLISHED_EVENT_LIST_REQUEST = "PUBLISHED_EVENT_LIST_REQUEST"
export const PUBLISHED_EVENT_LIST_SUCCESS = "PUBLISHED_EVENT_LIST_SUCCESS"
export const PUBLISHED_EVENT_LIST_FAIL = "PUBLISHED_EVENT_LIST_FAIL"

export const BUY_TICKET_REQUEST = "BUY_TICKET_REQUEST"
export const BUY_TICKET_SUCCESS = "BUY_TICKET_SUCCESS"
export const BUY_TICKET_FAIL = "BUY_TICKET_FAIL"
export const BUY_TICKET_COMPLETE = "BUY_TICKET_COMPLETE"

export const GET_AVAILABLE_TICKETS_REQUEST = "GET_AVAILABLE_TICKETS_REQUEST" 
export const GET_AVAILABLE_TICKETS_SUCCESS = "GET_AVAILABLE_TICKETS_SUCCESS" 
export const GET_AVAILABLE_TICKETS_FAIL = "GET_AVAILABLE_TICKETS_FAIL" 