export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';
export const CREATE_EVENT_COMPLETE = 'CREATE_EVENT_COMPLETE';

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';
export const UPDATE_EVENT_COMPLETE = 'UPDATE_EVENT_COMPLETE';


export const EVENT_DETAIL_REQUEST = "EVENT_DETAIL_REQUEST";
export const EVENT_DETAIL_SUCCESS = "EVENT_DETAIL_SUCCESS";
export const EVENT_DETAIL_FAIL = "EVENT_DETAIL_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST"; 
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS"; 
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";