export const EVENT_TICKETS_LIST_REQUEST = "EVENT_TICKETS_LIST_REQUEST";
export const EVENT_TICKETS_LIST_SUCCESS = "EVENT_TICKETS_LIST_SUCCESS";
export const EVENT_TICKETS_LIST_FAIL = "EVENT_TICKETS_LIST_FAIL";

export const CREATE_TICKETS_REQUEST = 'CREATE_TICKETS_REQUEST';
export const CREATE_TICKETS_SUCCESS = 'CREATE_TICKETS_SUCCESS';
export const CREATE_TICKETS_FAIL = 'CREATE_TICKETS_FAIL';
export const CREATE_TICKETS_COMPLETE = 'CREATE_TICKETS_COMPLETE';