export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const USER_EVENTS_LIST_REQUEST = "USER_EVENTS_LIST_REQUEST";
export const USER_EVENTS_LIST_SUCCESS = "USER_EVENTS_LIST_SUCCESS";
export const USER_EVENTS_LIST_FAIL = "USER_EVENTS_LIST_FAIL";




